### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by Rubender353** [meraki/dashboard-api-python#141] opened 2021-02-19 23:49 UTC
When I try to import meraki I get error such as below. Turns out that there is this weird character ï¿½ in lib\site-packages\meraki\api\switch.py. There are other files that have such weird characters. I am using latest python version, latest pip, and windows 10 1909

from .api.switch import Switch
line 1155
    """
       ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xa0 in position 243: invalid start byte

Code part that has weird character in switch.py
`    
def createNetworkSwitchRoutingMulticastRendezvousPoint(self, networkId: str, interfaceIp: str, multicastGroup: str):
        - networkId (string): (required)
        - interfaceIp (string): The�IP address of the interface where the RP needs to be created.
        - multicastGroup (string): 'Any', or the IP address of a multicast group
`

**Comment by TKIPisalegacycipher** [comment] 2021-02-21 18:40
Thank you @Rubender353 for reporting this. This is a known issue with a fix coming shortly. This is a duplicate of #140 so I'm closing this one--all further updates on #140.

**Closed by TKIPisalegacycipher** 2021-02-21 18:40 UTC
