### ISSUE TITLE
Missing the ability to query the network default RF profile (basic RF profile)

### ISSUE THREAD

**Issue by wowkmw** [meraki/dashboard-api-python#163] opened 2021-08-18 23:58 UTC
The API getNetworkWirelessRfProfiles only returns the non-basic RF profiles.
Some networks in our deployment only have the basic ones and for the purpose of network analysis, we need the ability to retrieve the settings of these basic RF profiles.
Would it be possible to add this functionality to the existing getNetworkWirelessRfProfiles API endpoint, as an additional argument like includeBasicProfiles=true?
![image](https://user-images.githubusercontent.com/33388262/129986915-944372aa-603c-4975-9a59-05cff7835db2.png)

**Comment by TKIPisalegacycipher** [comment] 2021-09-03 19:34
Hello @wowkmw , thanks for asking! This is a limitation of the current API itself, rather than the SDK. You can submit a feature request through the GUI's "give feedback" button. Since the SDK is working as designed, I'll close this issue.

**Closed by TKIPisalegacycipher** 2021-09-03 19:34 UTC
