### ISSUE TITLE
502 Bad Gateway for getNetworkClientsUsageHistories with large page

### ISSUE THREAD

**Issue by j-adamczyk** [meraki/dashboard-api-python#190] opened 2022-05-16 07:48 UTC
I am getting the following error when using Python SDK (synchronous version) with [getNetworkClientsUsageHistories](https://developer.cisco.com/meraki/api-latest/#!get-network-clients-usage-histories) endpoint with large number of entries per page, i.e. above 64 (docs say that 1000 is the limit):

```
  File "/home/airflow/.local/lib/python3.8/site-packages/meraki/api/networks.py", line 402, in getNetworkClientsUsageHistories
    return self._session.get_pages(metadata, resource, params, total_pages, direction)
  File "/home/airflow/.local/lib/python3.8/site-packages/meraki/rest_session.py", line 378, in _get_pages_legacy
    response = self.request(metadata, 'GET', url, params=params)
  File "/home/airflow/.local/lib/python3.8/site-packages/meraki/rest_session.py", line 243, in request
    raise APIError(metadata, response)
meraki.exceptions.APIError: networks, getNetworkClientsUsageHistories - 502 Bad Gateway, <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></cente
 ```

For very small pages (e.g. 3, 16, 32) it works, but returns only the first page, even when using `total_pages="all"`. It does work in all cases (<=32 and >32 client IDs) from Postman.

Whan can I do about this?

**Comment by j-adamczyk** [comment] 2022-05-16 09:20
I checked that Postman uses `n244` shard, instead of API Gateway. SDK does not work probably because routing is bugged.

Postman base URL that works: `https://n244.meraki.com/api/v1`. SDK base URL that does not work: `https://api.meraki.com/api/v1`.

After setting `self.base_url = "https://n244.meraki.com/api/v1"` in `RestSession` class instance it works. However, this should be fixed.

**Comment by TKIPisalegacycipher** [comment] 2022-07-01 23:05
Thanks for reporting this @j-adamczyk. In Postman, if you change `n244` to `api` in your base URL, does Postman have the same problem?

**Comment by TKIPisalegacycipher** [comment] 2022-08-27 00:40
Thanks @j-adamczyk. Since the issue doesn't happen with api.meraki.com via Postman, that tells me it's not an api.meraki.com-specific issue.

I checked out the API endpoint itself (i.e. the docs link you shared) and by design, it returns an array, wherein each item also contains a nested array called `usageHistory`. The perPage attribute will only limit the size of the top-level array. The `timespan` query param, however, will limit the size of `usageHistory`. I wonder if this issue is related to the Python `requests` library handling a certain payload size in conjunction with an auth redirect when the `usageHistory` array is very long, e.g. when the timespan is large. 

When you see this issue, what is the timespan you are using?

While using `api.meraki.com`, are you able to reproduce this problem with short timespans (e.g. 60 for 60 seconds)?

**Comment by j-adamczyk** [comment] 2022-09-06 08:50
I am using 24 hours timespan. Interestingly, with 24 hours timespan and page size 500 (so quite large payload) it works with `n244`, but not with `api`.

For 60 second timespan and page size 500, I get the same error, and even for timespan 30. However, combination of page size 32 and timespan of 60 seconds returns all pages.

**Comment by TKIPisalegacycipher** [comment] 2023-04-30 18:10
Would the request URI length happen to be over 8 KB?

**Comment by TKIPisalegacycipher** [comment] 2023-05-09 21:38
My best guess at this time is that there's an 8KB URI size limit, but this is happening at the API level, not the SDK level. This is not something we can fix from the SDK side, so closing this out.

I would recommend splitting those requests into separate queries where URIs are <8KB.

**Closed by TKIPisalegacycipher** 2023-05-09 21:38 UTC
